# This GitHub Action workflow runs a curl command on a schedule.

name: IPv4 Game

# This schedule runs the workflow every minute of every day.
# NOTE: GitHub Actions may occasionally skip a run if there are delays.
on:
  schedule:
    - cron: '* * * * *'
  # Also keeping workflow_dispatch to allow for manual runs for testing.
  workflow_dispatch:

jobs:
  claim-ip:
    runs-on: ubuntu-latest

    steps:
      # This single step runs the curl command.
      # Each time the workflow runs, it will be on a new runner,
      # likely with a different IP address.
      - name: Send claim request to ipv4.games
        run: |
          curl -s "https://ipv4.games/claim?name=yolo.gang"

